// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoDefine.proto

package zorg.game_scene.proto;

public final class ProtoDefine {
  private ProtoDefine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GamePlayerStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zorg.game_scene.proto.GamePlayerState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();

    /**
     * <code>optional bool online = 3;</code>
     */
    boolean getOnline();
  }
  /**
   * Protobuf type {@code zorg.game_scene.proto.GamePlayerState}
   */
  public  static final class GamePlayerState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zorg.game_scene.proto.GamePlayerState)
      GamePlayerStateOrBuilder {
    // Use GamePlayerState.newBuilder() to construct.
    private GamePlayerState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GamePlayerState() {
      x_ = 0;
      y_ = 0;
      online_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GamePlayerState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {

              online_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_GamePlayerState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_GamePlayerState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zorg.game_scene.proto.ProtoDefine.GamePlayerState.class, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int ONLINE_FIELD_NUMBER = 3;
    private boolean online_;
    /**
     * <code>optional bool online = 3;</code>
     */
    public boolean getOnline() {
      return online_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (online_ != false) {
        output.writeBool(3, online_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (online_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, online_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zorg.game_scene.proto.ProtoDefine.GamePlayerState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zorg.game_scene.proto.GamePlayerState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zorg.game_scene.proto.GamePlayerState)
        zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_GamePlayerState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_GamePlayerState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zorg.game_scene.proto.ProtoDefine.GamePlayerState.class, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder.class);
      }

      // Construct using zorg.game_scene.proto.ProtoDefine.GamePlayerState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        online_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_GamePlayerState_descriptor;
      }

      public zorg.game_scene.proto.ProtoDefine.GamePlayerState getDefaultInstanceForType() {
        return zorg.game_scene.proto.ProtoDefine.GamePlayerState.getDefaultInstance();
      }

      public zorg.game_scene.proto.ProtoDefine.GamePlayerState build() {
        zorg.game_scene.proto.ProtoDefine.GamePlayerState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zorg.game_scene.proto.ProtoDefine.GamePlayerState buildPartial() {
        zorg.game_scene.proto.ProtoDefine.GamePlayerState result = new zorg.game_scene.proto.ProtoDefine.GamePlayerState(this);
        result.x_ = x_;
        result.y_ = y_;
        result.online_ = online_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zorg.game_scene.proto.ProtoDefine.GamePlayerState) {
          return mergeFrom((zorg.game_scene.proto.ProtoDefine.GamePlayerState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zorg.game_scene.proto.ProtoDefine.GamePlayerState other) {
        if (other == zorg.game_scene.proto.ProtoDefine.GamePlayerState.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getOnline() != false) {
          setOnline(other.getOnline());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zorg.game_scene.proto.ProtoDefine.GamePlayerState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zorg.game_scene.proto.ProtoDefine.GamePlayerState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private boolean online_ ;
      /**
       * <code>optional bool online = 3;</code>
       */
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>optional bool online = 3;</code>
       */
      public Builder setOnline(boolean value) {
        
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool online = 3;</code>
       */
      public Builder clearOnline() {
        
        online_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:zorg.game_scene.proto.GamePlayerState)
    }

    // @@protoc_insertion_point(class_scope:zorg.game_scene.proto.GamePlayerState)
    private static final zorg.game_scene.proto.ProtoDefine.GamePlayerState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zorg.game_scene.proto.ProtoDefine.GamePlayerState();
    }

    public static zorg.game_scene.proto.ProtoDefine.GamePlayerState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GamePlayerState>
        PARSER = new com.google.protobuf.AbstractParser<GamePlayerState>() {
      public GamePlayerState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GamePlayerState(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GamePlayerState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GamePlayerState> getParserForType() {
      return PARSER;
    }

    public zorg.game_scene.proto.ProtoDefine.GamePlayerState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SceneStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zorg.game_scene.proto.SceneState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState> 
        getPlayerStatesList();
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    zorg.game_scene.proto.ProtoDefine.GamePlayerState getPlayerStates(int index);
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    int getPlayerStatesCount();
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    java.util.List<? extends zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder> 
        getPlayerStatesOrBuilderList();
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder getPlayerStatesOrBuilder(
        int index);

    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    java.util.List<java.lang.Long> getDisappearingPlayersList();
    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    int getDisappearingPlayersCount();
    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    long getDisappearingPlayers(int index);
  }
  /**
   * Protobuf type {@code zorg.game_scene.proto.SceneState}
   */
  public  static final class SceneState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zorg.game_scene.proto.SceneState)
      SceneStateOrBuilder {
    // Use SceneState.newBuilder() to construct.
    private SceneState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SceneState() {
      playerStates_ = java.util.Collections.emptyList();
      disappearingPlayers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SceneState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                playerStates_ = new java.util.ArrayList<zorg.game_scene.proto.ProtoDefine.GamePlayerState>();
                mutable_bitField0_ |= 0x00000001;
              }
              playerStates_.add(input.readMessage(zorg.game_scene.proto.ProtoDefine.GamePlayerState.parser(), extensionRegistry));
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                disappearingPlayers_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              disappearingPlayers_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                disappearingPlayers_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                disappearingPlayers_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          playerStates_ = java.util.Collections.unmodifiableList(playerStates_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          disappearingPlayers_ = java.util.Collections.unmodifiableList(disappearingPlayers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_SceneState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_SceneState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zorg.game_scene.proto.ProtoDefine.SceneState.class, zorg.game_scene.proto.ProtoDefine.SceneState.Builder.class);
    }

    public static final int PLAYERSTATES_FIELD_NUMBER = 1;
    private java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState> playerStates_;
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    public java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState> getPlayerStatesList() {
      return playerStates_;
    }
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    public java.util.List<? extends zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder> 
        getPlayerStatesOrBuilderList() {
      return playerStates_;
    }
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    public int getPlayerStatesCount() {
      return playerStates_.size();
    }
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    public zorg.game_scene.proto.ProtoDefine.GamePlayerState getPlayerStates(int index) {
      return playerStates_.get(index);
    }
    /**
     * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
     */
    public zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder getPlayerStatesOrBuilder(
        int index) {
      return playerStates_.get(index);
    }

    public static final int DISAPPEARINGPLAYERS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> disappearingPlayers_;
    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getDisappearingPlayersList() {
      return disappearingPlayers_;
    }
    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    public int getDisappearingPlayersCount() {
      return disappearingPlayers_.size();
    }
    /**
     * <code>repeated int64 disappearingPlayers = 2;</code>
     */
    public long getDisappearingPlayers(int index) {
      return disappearingPlayers_.get(index);
    }
    private int disappearingPlayersMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playerStates_.size(); i++) {
        output.writeMessage(1, playerStates_.get(i));
      }
      if (getDisappearingPlayersList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(disappearingPlayersMemoizedSerializedSize);
      }
      for (int i = 0; i < disappearingPlayers_.size(); i++) {
        output.writeInt64NoTag(disappearingPlayers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playerStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerStates_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < disappearingPlayers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(disappearingPlayers_.get(i));
        }
        size += dataSize;
        if (!getDisappearingPlayersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        disappearingPlayersMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.SceneState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zorg.game_scene.proto.ProtoDefine.SceneState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zorg.game_scene.proto.SceneState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zorg.game_scene.proto.SceneState)
        zorg.game_scene.proto.ProtoDefine.SceneStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_SceneState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_SceneState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zorg.game_scene.proto.ProtoDefine.SceneState.class, zorg.game_scene.proto.ProtoDefine.SceneState.Builder.class);
      }

      // Construct using zorg.game_scene.proto.ProtoDefine.SceneState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerStatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (playerStatesBuilder_ == null) {
          playerStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playerStatesBuilder_.clear();
        }
        disappearingPlayers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_SceneState_descriptor;
      }

      public zorg.game_scene.proto.ProtoDefine.SceneState getDefaultInstanceForType() {
        return zorg.game_scene.proto.ProtoDefine.SceneState.getDefaultInstance();
      }

      public zorg.game_scene.proto.ProtoDefine.SceneState build() {
        zorg.game_scene.proto.ProtoDefine.SceneState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zorg.game_scene.proto.ProtoDefine.SceneState buildPartial() {
        zorg.game_scene.proto.ProtoDefine.SceneState result = new zorg.game_scene.proto.ProtoDefine.SceneState(this);
        int from_bitField0_ = bitField0_;
        if (playerStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            playerStates_ = java.util.Collections.unmodifiableList(playerStates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playerStates_ = playerStates_;
        } else {
          result.playerStates_ = playerStatesBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          disappearingPlayers_ = java.util.Collections.unmodifiableList(disappearingPlayers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.disappearingPlayers_ = disappearingPlayers_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zorg.game_scene.proto.ProtoDefine.SceneState) {
          return mergeFrom((zorg.game_scene.proto.ProtoDefine.SceneState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zorg.game_scene.proto.ProtoDefine.SceneState other) {
        if (other == zorg.game_scene.proto.ProtoDefine.SceneState.getDefaultInstance()) return this;
        if (playerStatesBuilder_ == null) {
          if (!other.playerStates_.isEmpty()) {
            if (playerStates_.isEmpty()) {
              playerStates_ = other.playerStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayerStatesIsMutable();
              playerStates_.addAll(other.playerStates_);
            }
            onChanged();
          }
        } else {
          if (!other.playerStates_.isEmpty()) {
            if (playerStatesBuilder_.isEmpty()) {
              playerStatesBuilder_.dispose();
              playerStatesBuilder_ = null;
              playerStates_ = other.playerStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playerStatesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayerStatesFieldBuilder() : null;
            } else {
              playerStatesBuilder_.addAllMessages(other.playerStates_);
            }
          }
        }
        if (!other.disappearingPlayers_.isEmpty()) {
          if (disappearingPlayers_.isEmpty()) {
            disappearingPlayers_ = other.disappearingPlayers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDisappearingPlayersIsMutable();
            disappearingPlayers_.addAll(other.disappearingPlayers_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zorg.game_scene.proto.ProtoDefine.SceneState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zorg.game_scene.proto.ProtoDefine.SceneState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState> playerStates_ =
        java.util.Collections.emptyList();
      private void ensurePlayerStatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playerStates_ = new java.util.ArrayList<zorg.game_scene.proto.ProtoDefine.GamePlayerState>(playerStates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          zorg.game_scene.proto.ProtoDefine.GamePlayerState, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder, zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder> playerStatesBuilder_;

      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState> getPlayerStatesList() {
        if (playerStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playerStates_);
        } else {
          return playerStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public int getPlayerStatesCount() {
        if (playerStatesBuilder_ == null) {
          return playerStates_.size();
        } else {
          return playerStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public zorg.game_scene.proto.ProtoDefine.GamePlayerState getPlayerStates(int index) {
        if (playerStatesBuilder_ == null) {
          return playerStates_.get(index);
        } else {
          return playerStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder setPlayerStates(
          int index, zorg.game_scene.proto.ProtoDefine.GamePlayerState value) {
        if (playerStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatesIsMutable();
          playerStates_.set(index, value);
          onChanged();
        } else {
          playerStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder setPlayerStates(
          int index, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder builderForValue) {
        if (playerStatesBuilder_ == null) {
          ensurePlayerStatesIsMutable();
          playerStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder addPlayerStates(zorg.game_scene.proto.ProtoDefine.GamePlayerState value) {
        if (playerStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatesIsMutable();
          playerStates_.add(value);
          onChanged();
        } else {
          playerStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder addPlayerStates(
          int index, zorg.game_scene.proto.ProtoDefine.GamePlayerState value) {
        if (playerStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerStatesIsMutable();
          playerStates_.add(index, value);
          onChanged();
        } else {
          playerStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder addPlayerStates(
          zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder builderForValue) {
        if (playerStatesBuilder_ == null) {
          ensurePlayerStatesIsMutable();
          playerStates_.add(builderForValue.build());
          onChanged();
        } else {
          playerStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder addPlayerStates(
          int index, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder builderForValue) {
        if (playerStatesBuilder_ == null) {
          ensurePlayerStatesIsMutable();
          playerStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder addAllPlayerStates(
          java.lang.Iterable<? extends zorg.game_scene.proto.ProtoDefine.GamePlayerState> values) {
        if (playerStatesBuilder_ == null) {
          ensurePlayerStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, playerStates_);
          onChanged();
        } else {
          playerStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder clearPlayerStates() {
        if (playerStatesBuilder_ == null) {
          playerStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playerStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public Builder removePlayerStates(int index) {
        if (playerStatesBuilder_ == null) {
          ensurePlayerStatesIsMutable();
          playerStates_.remove(index);
          onChanged();
        } else {
          playerStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder getPlayerStatesBuilder(
          int index) {
        return getPlayerStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder getPlayerStatesOrBuilder(
          int index) {
        if (playerStatesBuilder_ == null) {
          return playerStates_.get(index);  } else {
          return playerStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public java.util.List<? extends zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder> 
           getPlayerStatesOrBuilderList() {
        if (playerStatesBuilder_ != null) {
          return playerStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playerStates_);
        }
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder addPlayerStatesBuilder() {
        return getPlayerStatesFieldBuilder().addBuilder(
            zorg.game_scene.proto.ProtoDefine.GamePlayerState.getDefaultInstance());
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder addPlayerStatesBuilder(
          int index) {
        return getPlayerStatesFieldBuilder().addBuilder(
            index, zorg.game_scene.proto.ProtoDefine.GamePlayerState.getDefaultInstance());
      }
      /**
       * <code>repeated .zorg.game_scene.proto.GamePlayerState playerStates = 1;</code>
       */
      public java.util.List<zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder> 
           getPlayerStatesBuilderList() {
        return getPlayerStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          zorg.game_scene.proto.ProtoDefine.GamePlayerState, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder, zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder> 
          getPlayerStatesFieldBuilder() {
        if (playerStatesBuilder_ == null) {
          playerStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              zorg.game_scene.proto.ProtoDefine.GamePlayerState, zorg.game_scene.proto.ProtoDefine.GamePlayerState.Builder, zorg.game_scene.proto.ProtoDefine.GamePlayerStateOrBuilder>(
                  playerStates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          playerStates_ = null;
        }
        return playerStatesBuilder_;
      }

      private java.util.List<java.lang.Long> disappearingPlayers_ = java.util.Collections.emptyList();
      private void ensureDisappearingPlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          disappearingPlayers_ = new java.util.ArrayList<java.lang.Long>(disappearingPlayers_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getDisappearingPlayersList() {
        return java.util.Collections.unmodifiableList(disappearingPlayers_);
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public int getDisappearingPlayersCount() {
        return disappearingPlayers_.size();
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public long getDisappearingPlayers(int index) {
        return disappearingPlayers_.get(index);
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public Builder setDisappearingPlayers(
          int index, long value) {
        ensureDisappearingPlayersIsMutable();
        disappearingPlayers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public Builder addDisappearingPlayers(long value) {
        ensureDisappearingPlayersIsMutable();
        disappearingPlayers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public Builder addAllDisappearingPlayers(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDisappearingPlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, disappearingPlayers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 disappearingPlayers = 2;</code>
       */
      public Builder clearDisappearingPlayers() {
        disappearingPlayers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:zorg.game_scene.proto.SceneState)
    }

    // @@protoc_insertion_point(class_scope:zorg.game_scene.proto.SceneState)
    private static final zorg.game_scene.proto.ProtoDefine.SceneState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zorg.game_scene.proto.ProtoDefine.SceneState();
    }

    public static zorg.game_scene.proto.ProtoDefine.SceneState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SceneState>
        PARSER = new com.google.protobuf.AbstractParser<SceneState>() {
      public SceneState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SceneState(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SceneState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SceneState> getParserForType() {
      return PARSER;
    }

    public zorg.game_scene.proto.ProtoDefine.SceneState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnterOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zorg.game_scene.proto.EnterOperation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 toPosX = 1;</code>
     */
    int getToPosX();

    /**
     * <code>optional int32 toPosY = 2;</code>
     */
    int getToPosY();
  }
  /**
   * Protobuf type {@code zorg.game_scene.proto.EnterOperation}
   */
  public  static final class EnterOperation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zorg.game_scene.proto.EnterOperation)
      EnterOperationOrBuilder {
    // Use EnterOperation.newBuilder() to construct.
    private EnterOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EnterOperation() {
      toPosX_ = 0;
      toPosY_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EnterOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              toPosX_ = input.readInt32();
              break;
            }
            case 16: {

              toPosY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_EnterOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_EnterOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zorg.game_scene.proto.ProtoDefine.EnterOperation.class, zorg.game_scene.proto.ProtoDefine.EnterOperation.Builder.class);
    }

    public static final int TOPOSX_FIELD_NUMBER = 1;
    private int toPosX_;
    /**
     * <code>optional int32 toPosX = 1;</code>
     */
    public int getToPosX() {
      return toPosX_;
    }

    public static final int TOPOSY_FIELD_NUMBER = 2;
    private int toPosY_;
    /**
     * <code>optional int32 toPosY = 2;</code>
     */
    public int getToPosY() {
      return toPosY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (toPosX_ != 0) {
        output.writeInt32(1, toPosX_);
      }
      if (toPosY_ != 0) {
        output.writeInt32(2, toPosY_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (toPosX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, toPosX_);
      }
      if (toPosY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, toPosY_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.EnterOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zorg.game_scene.proto.ProtoDefine.EnterOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zorg.game_scene.proto.EnterOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zorg.game_scene.proto.EnterOperation)
        zorg.game_scene.proto.ProtoDefine.EnterOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_EnterOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_EnterOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zorg.game_scene.proto.ProtoDefine.EnterOperation.class, zorg.game_scene.proto.ProtoDefine.EnterOperation.Builder.class);
      }

      // Construct using zorg.game_scene.proto.ProtoDefine.EnterOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        toPosX_ = 0;

        toPosY_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_EnterOperation_descriptor;
      }

      public zorg.game_scene.proto.ProtoDefine.EnterOperation getDefaultInstanceForType() {
        return zorg.game_scene.proto.ProtoDefine.EnterOperation.getDefaultInstance();
      }

      public zorg.game_scene.proto.ProtoDefine.EnterOperation build() {
        zorg.game_scene.proto.ProtoDefine.EnterOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zorg.game_scene.proto.ProtoDefine.EnterOperation buildPartial() {
        zorg.game_scene.proto.ProtoDefine.EnterOperation result = new zorg.game_scene.proto.ProtoDefine.EnterOperation(this);
        result.toPosX_ = toPosX_;
        result.toPosY_ = toPosY_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zorg.game_scene.proto.ProtoDefine.EnterOperation) {
          return mergeFrom((zorg.game_scene.proto.ProtoDefine.EnterOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zorg.game_scene.proto.ProtoDefine.EnterOperation other) {
        if (other == zorg.game_scene.proto.ProtoDefine.EnterOperation.getDefaultInstance()) return this;
        if (other.getToPosX() != 0) {
          setToPosX(other.getToPosX());
        }
        if (other.getToPosY() != 0) {
          setToPosY(other.getToPosY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zorg.game_scene.proto.ProtoDefine.EnterOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zorg.game_scene.proto.ProtoDefine.EnterOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int toPosX_ ;
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public int getToPosX() {
        return toPosX_;
      }
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public Builder setToPosX(int value) {
        
        toPosX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public Builder clearToPosX() {
        
        toPosX_ = 0;
        onChanged();
        return this;
      }

      private int toPosY_ ;
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public int getToPosY() {
        return toPosY_;
      }
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public Builder setToPosY(int value) {
        
        toPosY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public Builder clearToPosY() {
        
        toPosY_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:zorg.game_scene.proto.EnterOperation)
    }

    // @@protoc_insertion_point(class_scope:zorg.game_scene.proto.EnterOperation)
    private static final zorg.game_scene.proto.ProtoDefine.EnterOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zorg.game_scene.proto.ProtoDefine.EnterOperation();
    }

    public static zorg.game_scene.proto.ProtoDefine.EnterOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnterOperation>
        PARSER = new com.google.protobuf.AbstractParser<EnterOperation>() {
      public EnterOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new EnterOperation(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<EnterOperation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnterOperation> getParserForType() {
      return PARSER;
    }

    public zorg.game_scene.proto.ProtoDefine.EnterOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoveOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zorg.game_scene.proto.MoveOperation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 toPosX = 1;</code>
     */
    int getToPosX();

    /**
     * <code>optional int32 toPosY = 2;</code>
     */
    int getToPosY();
  }
  /**
   * Protobuf type {@code zorg.game_scene.proto.MoveOperation}
   */
  public  static final class MoveOperation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zorg.game_scene.proto.MoveOperation)
      MoveOperationOrBuilder {
    // Use MoveOperation.newBuilder() to construct.
    private MoveOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MoveOperation() {
      toPosX_ = 0;
      toPosY_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MoveOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              toPosX_ = input.readInt32();
              break;
            }
            case 16: {

              toPosY_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_MoveOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_MoveOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zorg.game_scene.proto.ProtoDefine.MoveOperation.class, zorg.game_scene.proto.ProtoDefine.MoveOperation.Builder.class);
    }

    public static final int TOPOSX_FIELD_NUMBER = 1;
    private int toPosX_;
    /**
     * <code>optional int32 toPosX = 1;</code>
     */
    public int getToPosX() {
      return toPosX_;
    }

    public static final int TOPOSY_FIELD_NUMBER = 2;
    private int toPosY_;
    /**
     * <code>optional int32 toPosY = 2;</code>
     */
    public int getToPosY() {
      return toPosY_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (toPosX_ != 0) {
        output.writeInt32(1, toPosX_);
      }
      if (toPosY_ != 0) {
        output.writeInt32(2, toPosY_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (toPosX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, toPosX_);
      }
      if (toPosY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, toPosY_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.MoveOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zorg.game_scene.proto.ProtoDefine.MoveOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zorg.game_scene.proto.MoveOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zorg.game_scene.proto.MoveOperation)
        zorg.game_scene.proto.ProtoDefine.MoveOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_MoveOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_MoveOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zorg.game_scene.proto.ProtoDefine.MoveOperation.class, zorg.game_scene.proto.ProtoDefine.MoveOperation.Builder.class);
      }

      // Construct using zorg.game_scene.proto.ProtoDefine.MoveOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        toPosX_ = 0;

        toPosY_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_MoveOperation_descriptor;
      }

      public zorg.game_scene.proto.ProtoDefine.MoveOperation getDefaultInstanceForType() {
        return zorg.game_scene.proto.ProtoDefine.MoveOperation.getDefaultInstance();
      }

      public zorg.game_scene.proto.ProtoDefine.MoveOperation build() {
        zorg.game_scene.proto.ProtoDefine.MoveOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zorg.game_scene.proto.ProtoDefine.MoveOperation buildPartial() {
        zorg.game_scene.proto.ProtoDefine.MoveOperation result = new zorg.game_scene.proto.ProtoDefine.MoveOperation(this);
        result.toPosX_ = toPosX_;
        result.toPosY_ = toPosY_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zorg.game_scene.proto.ProtoDefine.MoveOperation) {
          return mergeFrom((zorg.game_scene.proto.ProtoDefine.MoveOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zorg.game_scene.proto.ProtoDefine.MoveOperation other) {
        if (other == zorg.game_scene.proto.ProtoDefine.MoveOperation.getDefaultInstance()) return this;
        if (other.getToPosX() != 0) {
          setToPosX(other.getToPosX());
        }
        if (other.getToPosY() != 0) {
          setToPosY(other.getToPosY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zorg.game_scene.proto.ProtoDefine.MoveOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zorg.game_scene.proto.ProtoDefine.MoveOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int toPosX_ ;
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public int getToPosX() {
        return toPosX_;
      }
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public Builder setToPosX(int value) {
        
        toPosX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 toPosX = 1;</code>
       */
      public Builder clearToPosX() {
        
        toPosX_ = 0;
        onChanged();
        return this;
      }

      private int toPosY_ ;
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public int getToPosY() {
        return toPosY_;
      }
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public Builder setToPosY(int value) {
        
        toPosY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 toPosY = 2;</code>
       */
      public Builder clearToPosY() {
        
        toPosY_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:zorg.game_scene.proto.MoveOperation)
    }

    // @@protoc_insertion_point(class_scope:zorg.game_scene.proto.MoveOperation)
    private static final zorg.game_scene.proto.ProtoDefine.MoveOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zorg.game_scene.proto.ProtoDefine.MoveOperation();
    }

    public static zorg.game_scene.proto.ProtoDefine.MoveOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoveOperation>
        PARSER = new com.google.protobuf.AbstractParser<MoveOperation>() {
      public MoveOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MoveOperation(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MoveOperation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoveOperation> getParserForType() {
      return PARSER;
    }

    public zorg.game_scene.proto.ProtoDefine.MoveOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LeaveOperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zorg.game_scene.proto.LeaveOperation)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code zorg.game_scene.proto.LeaveOperation}
   */
  public  static final class LeaveOperation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zorg.game_scene.proto.LeaveOperation)
      LeaveOperationOrBuilder {
    // Use LeaveOperation.newBuilder() to construct.
    private LeaveOperation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LeaveOperation() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LeaveOperation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_LeaveOperation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_LeaveOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zorg.game_scene.proto.ProtoDefine.LeaveOperation.class, zorg.game_scene.proto.ProtoDefine.LeaveOperation.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(zorg.game_scene.proto.ProtoDefine.LeaveOperation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zorg.game_scene.proto.LeaveOperation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zorg.game_scene.proto.LeaveOperation)
        zorg.game_scene.proto.ProtoDefine.LeaveOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_LeaveOperation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_LeaveOperation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zorg.game_scene.proto.ProtoDefine.LeaveOperation.class, zorg.game_scene.proto.ProtoDefine.LeaveOperation.Builder.class);
      }

      // Construct using zorg.game_scene.proto.ProtoDefine.LeaveOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zorg.game_scene.proto.ProtoDefine.internal_static_zorg_game_scene_proto_LeaveOperation_descriptor;
      }

      public zorg.game_scene.proto.ProtoDefine.LeaveOperation getDefaultInstanceForType() {
        return zorg.game_scene.proto.ProtoDefine.LeaveOperation.getDefaultInstance();
      }

      public zorg.game_scene.proto.ProtoDefine.LeaveOperation build() {
        zorg.game_scene.proto.ProtoDefine.LeaveOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zorg.game_scene.proto.ProtoDefine.LeaveOperation buildPartial() {
        zorg.game_scene.proto.ProtoDefine.LeaveOperation result = new zorg.game_scene.proto.ProtoDefine.LeaveOperation(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zorg.game_scene.proto.ProtoDefine.LeaveOperation) {
          return mergeFrom((zorg.game_scene.proto.ProtoDefine.LeaveOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zorg.game_scene.proto.ProtoDefine.LeaveOperation other) {
        if (other == zorg.game_scene.proto.ProtoDefine.LeaveOperation.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zorg.game_scene.proto.ProtoDefine.LeaveOperation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zorg.game_scene.proto.ProtoDefine.LeaveOperation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:zorg.game_scene.proto.LeaveOperation)
    }

    // @@protoc_insertion_point(class_scope:zorg.game_scene.proto.LeaveOperation)
    private static final zorg.game_scene.proto.ProtoDefine.LeaveOperation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new zorg.game_scene.proto.ProtoDefine.LeaveOperation();
    }

    public static zorg.game_scene.proto.ProtoDefine.LeaveOperation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LeaveOperation>
        PARSER = new com.google.protobuf.AbstractParser<LeaveOperation>() {
      public LeaveOperation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new LeaveOperation(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<LeaveOperation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaveOperation> getParserForType() {
      return PARSER;
    }

    public zorg.game_scene.proto.ProtoDefine.LeaveOperation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zorg_game_scene_proto_GamePlayerState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zorg_game_scene_proto_GamePlayerState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zorg_game_scene_proto_SceneState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zorg_game_scene_proto_SceneState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zorg_game_scene_proto_EnterOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zorg_game_scene_proto_EnterOperation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zorg_game_scene_proto_MoveOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zorg_game_scene_proto_MoveOperation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_zorg_game_scene_proto_LeaveOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zorg_game_scene_proto_LeaveOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProtoDefine.proto\022\025zorg.game_scene.pro" +
      "to\"7\n\017GamePlayerState\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 " +
      "\001(\005\022\016\n\006online\030\003 \001(\010\"g\n\nSceneState\022<\n\014pla" +
      "yerStates\030\001 \003(\0132&.zorg.game_scene.proto." +
      "GamePlayerState\022\033\n\023disappearingPlayers\030\002" +
      " \003(\003\"0\n\016EnterOperation\022\016\n\006toPosX\030\001 \001(\005\022\016" +
      "\n\006toPosY\030\002 \001(\005\"/\n\rMoveOperation\022\016\n\006toPos" +
      "X\030\001 \001(\005\022\016\n\006toPosY\030\002 \001(\005\"\020\n\016LeaveOperatio" +
      "nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_zorg_game_scene_proto_GamePlayerState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zorg_game_scene_proto_GamePlayerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zorg_game_scene_proto_GamePlayerState_descriptor,
        new java.lang.String[] { "X", "Y", "Online", });
    internal_static_zorg_game_scene_proto_SceneState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zorg_game_scene_proto_SceneState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zorg_game_scene_proto_SceneState_descriptor,
        new java.lang.String[] { "PlayerStates", "DisappearingPlayers", });
    internal_static_zorg_game_scene_proto_EnterOperation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zorg_game_scene_proto_EnterOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zorg_game_scene_proto_EnterOperation_descriptor,
        new java.lang.String[] { "ToPosX", "ToPosY", });
    internal_static_zorg_game_scene_proto_MoveOperation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zorg_game_scene_proto_MoveOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zorg_game_scene_proto_MoveOperation_descriptor,
        new java.lang.String[] { "ToPosX", "ToPosY", });
    internal_static_zorg_game_scene_proto_LeaveOperation_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_zorg_game_scene_proto_LeaveOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zorg_game_scene_proto_LeaveOperation_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
